<a href="https://colab.research.google.com/github/morozova111/SvetMorozova/blob/main/%D0%9A%D0%BE%D1%80%D1%80%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D1%8F_%D0%A1%D0%BF%D0%B8%D1%80%D0%BC%D0%B5%D0%BD%D0%B0%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


В статистике корреляция относится к силе и направлению связи между двумя переменными. Значение коэффициента корреляции может варьироваться от -1 до 1 со следующими интерпретациями:

    -1: идеальная отрицательная связь между двумя переменными
    0: нет связи между двумя переменными
    1: идеальная положительная связь между двумя переменными

Он применяется для выявления взаимосвязи между двумя параметрами.  
Корреляция Спирмена не предполагает нормального распределения обоих наборов данных

In [13]:
import numpy as np
import pandas as pd
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from scipy. stats import pearsonr
import pylab


In [5]:
from scipy import stats

stats.spearmanr([1,2,3,4,5], [5,6,7,8,7])# 

SpearmanrResult(correlation=0.8207826816681233, pvalue=0.08858700531354381)

In [8]:

rng = np.random.default_rng()

x2n = rng.standard_normal((100, 2))

y2n = rng.standard_normal((100, 2))

stats.spearmanr(x2n)

SpearmanrResult(correlation=0.20950495049504947, pvalue=0.036439804905923794)

In [9]:
stats.spearmanr(x2n[:,0], x2n[:,1])

SpearmanrResult(correlation=0.20950495049504947, pvalue=0.036439804905923794)

In [17]:
rho, pval = stats.spearmanr(x2n, y2n)

In [18]:
rho

array([[ 1.        ,  0.20950495, -0.04326433, -0.06269427],
       [ 0.20950495,  1.        , -0.10275428,  0.01911791],
       [-0.04326433, -0.10275428,  1.        ,  0.04738074],
       [-0.06269427,  0.01911791,  0.04738074,  1.        ]])

In [19]:
pval

array([[0.        , 0.0364398 , 0.66908503, 0.53547473],
       [0.0364398 , 0.        , 0.30900133, 0.85025525],
       [0.66908503, 0.30900133, 0.        , 0.63970343],
       [0.53547473, 0.85025525, 0.63970343, 0.        ]])

In [20]:
rho, pval = stats.spearmanr(x2n.T, y2n.T, axis=1)

In [21]:
rho

array([[ 1.        ,  0.20950495, -0.04326433, -0.06269427],
       [ 0.20950495,  1.        , -0.10275428,  0.01911791],
       [-0.04326433, -0.10275428,  1.        ,  0.04738074],
       [-0.06269427,  0.01911791,  0.04738074,  1.        ]])

In [22]:
stats.spearmanr(x2n, y2n, axis=None)

SpearmanrResult(correlation=-0.02043201080027001, pvalue=0.7739813255119365)